# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 624)
        MainWindow.setWindowIcon(QtGui.QIcon('logo.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(350, 0, 258, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.LastSourceDirectoryLBL = QtWidgets.QLabel(self.centralwidget)
        self.LastSourceDirectoryLBL.setGeometry(QtCore.QRect(20, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LastSourceDirectoryLBL.setFont(font)
        self.LastSourceDirectoryLBL.setObjectName("LastSourceDirectoryLBL")
        self.LastSourceDirectory = QtWidgets.QTextEdit(self.centralwidget)
        self.LastSourceDirectory.setGeometry(QtCore.QRect(20, 90, 821, 31))
        self.LastSourceDirectory.setObjectName("LastSourceDirectory")
        self.LoadBTN = QtWidgets.QPushButton(self.centralwidget)
        self.LoadBTN.setGeometry(QtCore.QRect(860, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LoadBTN.setFont(font)
        self.LoadBTN.setObjectName("LoadBTN")
        self.FilesToRenameLBL = QtWidgets.QLabel(self.centralwidget)
        self.FilesToRenameLBL.setGeometry(QtCore.QRect(20, 150, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FilesToRenameLBL.setFont(font)
        self.FilesToRenameLBL.setObjectName("FilesToRenameLBL")
        self.RenamedFilesLBL = QtWidgets.QLabel(self.centralwidget)
        self.RenamedFilesLBL.setGeometry(QtCore.QRect(490, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RenamedFilesLBL.setFont(font)
        self.RenamedFilesLBL.setObjectName("RenamedFilesLBL")
        self.FilenamePrefixLBL = QtWidgets.QLabel(self.centralwidget)
        self.FilenamePrefixLBL.setGeometry(QtCore.QRect(20, 500, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FilenamePrefixLBL.setFont(font)
        self.FilenamePrefixLBL.setObjectName("FilenamePrefixLBL")
        self.FilenamePrefix = QtWidgets.QTextEdit(self.centralwidget)
        self.FilenamePrefix.setGeometry(QtCore.QRect(20, 540, 791, 31))
        self.FilenamePrefix.setObjectName("FilenamePrefix")
        self.ExtensionLBL = QtWidgets.QLabel(self.centralwidget)
        self.ExtensionLBL.setGeometry(QtCore.QRect(820, 540, 41, 31))
        self.ExtensionLBL.setText("")
        self.ExtensionLBL.setObjectName("ExtensionLBL")
        self.RenameBTN = QtWidgets.QPushButton(self.centralwidget)
        self.RenameBTN.setGeometry(QtCore.QRect(870, 540, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RenameBTN.setFont(font)
        self.RenameBTN.setObjectName("RenameBTN")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 580, 931, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 180, 441, 321))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(490, 180, 441, 321))
        self.listWidget_2.setObjectName("listWidget_2")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bulk Rename Utility"))
        self.Title.setText(_translate("MainWindow", "Bulk Rename Utility"))
        self.LastSourceDirectoryLBL.setText(_translate("MainWindow", "Last Source Directory:"))
        self.LoadBTN.setText(_translate("MainWindow", "Load!"))
        self.FilesToRenameLBL.setText(_translate("MainWindow", "Files to Rename:"))
        self.RenamedFilesLBL.setText(_translate("MainWindow", "Renamed Files:"))
        self.FilenamePrefixLBL.setText(_translate("MainWindow", "Filename Prefix:"))
        self.FilenamePrefix.setPlaceholderText(_translate("MainWindow", "Enter new filename here"))
        self.RenameBTN.setText(_translate("MainWindow", "Rename"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
